In [1]:
import polars as pl

In [2]:
df = pl.read_parquet(r"G:\coding\python\web_scraping\Youm7\youm7_scrape\data\intermediate\reports.parquet")

In [32]:
df['url', 'content'].write_csv("../data/processed/politics_content.csv", include_bom=True)

In [3]:
df.shape

(409808, 9)

In [6]:
df.n_unique()

409400

In [5]:
df.describe()

shape: (9, 10)
┌────────────┬────────────┬───────────────┬──────────┬───┬────────┬──────────────┬────────┬────────┐
│ statistic  ┆ article_id ┆ url           ┆ category ┆ … ┆ author ┆ content      ┆ tags   ┆ media  │
│ ---        ┆ ---        ┆ ---           ┆ ---      ┆   ┆ ---    ┆ ---          ┆ ---    ┆ ---    │
│ str        ┆ str        ┆ str           ┆ str      ┆   ┆ str    ┆ str          ┆ f64    ┆ f64    │
╞════════════╪════════════╪═══════════════╪══════════╪═══╪════════╪══════════════╪════════╪════════╡
│ count      ┆ 1826       ┆ 1826          ┆ 1826     ┆ … ┆ 0      ┆ 1826         ┆ 1826.0 ┆ 1826.0 │
│ null_count ┆ 0          ┆ 0             ┆ 0        ┆ … ┆ 1826   ┆ 0            ┆ 0.0    ┆ 0.0    │
│ mean       ┆ null       ┆ null          ┆ null     ┆ … ┆ null   ┆ null         ┆ null   ┆ null   │
│ std        ┆ null       ┆ null          ┆ null     ┆ … ┆ null   ┆ null         ┆ null   ┆ null   │
│ min        ┆ 1029939    ┆ https://www.y ┆ سياسة    ┆ … ┆ null   ┆ " خيانة      ┆ null   ┆ null   │
│            ┆            ┆ oum7.com/stor ┆          ┆   ┆        ┆ الوطن" جريمة ┆        ┆        │
│            ┆            ┆ y/20…         ┆          ┆   ┆        ┆ لا تغتفر …    ┆        ┆        │
│ 25%        ┆ null       ┆ null          ┆ null     ┆ … ┆ null   ┆ null         ┆ null   ┆ null   │
│ 50%        ┆ null       ┆ null          ┆ null     ┆ … ┆ null   ┆ null         ┆ null   ┆ null   │
│ 75%        ┆ null       ┆ null          ┆ null     ┆ … ┆ null   ┆ null         ┆ null   ┆ null   │
│ max        ┆ 7344625    ┆ https://www.y ┆ سياسة    ┆ … ┆ null   ┆ يوافق اليوم  ┆ null   ┆ null   │
│            ┆            ┆ oum7.com/stor ┆          ┆   ┆        ┆ الأثنين،      ┆        ┆        │
│            ┆            ┆ y/20…         ┆          ┆   ┆        ┆ الذكرى ال…   ┆        ┆        │
└────────────┴────────────┴───────────────┴──────────┴───┴────────┴──────────────┴────────┴────────┘

In [4]:
df['media'].head(1)

shape: (1,)
Series: 'media' [list[struct[5]]]
[
	[{"image","https://img.youm7.com/large/202603200723112311_34.jpg","الجد السند.. جد يحمل حفيده من ذوي الهمم بصلاة العيد فى مسجد عمرو بن العاص","الجد السند.. جد يحمل حفيده من ذوي الهمم بصلاة العيد فى مسجد عمرو بن العاص","internal"}, {"image","https://img.youm7.com/ArticleImgs/2026/3/20/42344-251467-186695.jpg","251467-186695","251467-186695","internal"}, … {"image","https://img.youm7.com/Medium/202603200649324932_12603.jpg",null," جد يحمل حفيده من ذوي الهمم بصلاة العيد","internal"}]
]

In [5]:
df.filter(df['content'] == "")

shape: (0, 9)
┌────────────┬─────┬──────────┬───────┬───┬────────┬─────────┬───────────┬─────────────────┐
│ article_id ┆ url ┆ category ┆ title ┆ … ┆ author ┆ content ┆ tags      ┆ media           │
│ ---        ┆ --- ┆ ---      ┆ ---   ┆   ┆ ---    ┆ ---     ┆ ---       ┆ ---             │
│ str        ┆ str ┆ str      ┆ str   ┆   ┆ str    ┆ str     ┆ list[str] ┆ list[struct[5]] │
╞════════════╪═════╪══════════╪═══════╪═══╪════════╪═════════╪═══════════╪═════════════════╡
└────────────┴─────┴──────────┴───────┴───┴────────┴─────────┴───────────┴─────────────────┘

In [6]:
df.columns

['article_id',
 'url',
 'category',
 'title',
 'publish_date',
 'author',
 'content',
 'tags',
 'media']

In [ ]:
df.head(2)

In [40]:
df['content'].unique()

shape: (276_377,)
Series: 'content' [str]
[
	"أكد النائب تامر عبدالقادر، عضو…
	"قال النائب مصطفى بكرى، عضو مجل…
	"وجهت النائبة شادية ثابت، عضو م…
	"عبرت الفنانة والمطربة الكبيرة …
	"قال العميد خالد عكاشة مدير الم…
	…
	"قال الأديب الدكتور علاء الأسوا…
	"ترأس الدكتور حازم الببلاوى، رئ…
	"نعت تنسيقية شباب الأحزاب والسي…
	"اعتبر حسام فودة، عضو المكتب ال…
	"شارك الدكتور باسل عادل رئيس حز…
]

In [22]:
no_author_urls_array = df.filter(df["author"].is_not_null() == False).select("url").to_numpy()

print(no_author_urls_array)

# Its okay I checked the urls where author is null. They just don't have an author.

[['https://www.youm7.com/story/2026/3/16/%D8%A8%D8%B1%D8%AC-%D8%A7%D9%84%D9%82%D9%88%D8%B3-%D8%AD%D8%B8%D9%83-%D8%A7%D9%84%D9%8A%D9%88%D9%85-%D8%A7%D9%84%D8%A5%D8%AB%D9%86%D9%8A%D9%86-16-%D9%85%D8%A7%D8%B1%D8%B3-%D8%B3%D8%B9%D8%A7%D8%AF%D8%A9-%D9%85%D8%AA%D8%AC%D8%AF%D8%AF%D8%A9/7341099']
 ['https://www.youm7.com/story/2026/3/16/%D8%A8%D8%B1%D8%AC-%D8%A7%D9%84%D8%AC%D8%AF%D9%89-%D8%AD%D8%B8%D9%83-%D8%A7%D9%84%D9%8A%D9%88%D9%85-%D8%A7%D9%84%D8%A5%D8%AB%D9%86%D9%8A%D9%86-16-%D9%85%D8%A7%D8%B1%D8%B3-%D9%82%D8%B1%D8%A7%D8%B1%D8%A7%D8%AA-%D9%85%D8%AF%D8%B1%D9%88%D8%B3%D8%A9/7341094']
 ['https://www.youm7.com/story/2026/3/17/%D8%A8%D8%B1%D8%AC-%D8%A7%D9%84%D8%AB%D9%88%D8%B1-%D8%AD%D8%B8%D9%83-%D8%A7%D9%84%D9%8A%D9%88%D9%85-%D8%A7%D9%84%D8%AB%D9%84%D8%A7%D8%AB%D8%A7%D8%A1-17-%D9%85%D8%A7%D8%B1%D8%B3-%D8%AE%D8%B7%D9%88%D8%A7%D8%AA-%D8%AB%D8%A7%D8%A8%D8%AA%D8%A9/7340909']
 ...
 ['https://www.youm7.com/story/2015/6/9/%D8%AD%D8%B8%D9%83-%D8%A7%D9%84%D9%8A%D9%88%D9%85-%D8%A7%D9%84%D8%AB%D9%84%D8%A7%D8%AB%D8%A7%D8%A1-9-%E2%80%93-6-2015/2217060']
 ['https://www.youm7.com/story/2015/5/26/%D8%AA%D9%88%D9%82%D8%B9%D8%A7%D8%AA-%D8%A7%D9%84%D8%A3%D8%A8%D8%B1%D8%A7%D8%AC-%D8%A7%D9%84%D9%8A%D9%88%D9%85-%D8%A7%D9%84%D8%AB%D9%84%D8%A7%D8%AB%D8%A7%D8%A1-2015-5-26/2197528']
 ['https://www.youm7.com/story/2015/5/29/%D8%AA%D9%88%D9%82%D8%B9%D8%A7%D8%AA-%D8%A7%D9%84%D8%A3%D8%A8%D8%B1%D8%A7%D8%AC-%D9%8A%D9%88%D9%85-%D8%A7%D9%84%D8%AC%D9%85%D8%B9%D8%A9-2015-5-29/2201889']]

In [7]:
df['publish_date']

shape: (409_808,)
Series: 'publish_date' [str]
[
	"الجمعة، 20 مارس 2026 07:27 ص"
	"الجمعة، 20 مارس 2026 08:11 ص"
	"الجمعة، 20 مارس 2026 08:00 ص"
	"الجمعة، 20 مارس 2026 07:20 ص"
	"الجمعة، 20 مارس 2026 07:15 ص"
	…
	"الثلاثاء، 17 يوليو 2012 01:39 …
	"الأربعاء، 02 أغسطس 2017 06:19 …
	"الثلاثاء، 17 يوليو 2012 01:26 …
	"الإثنين، 16 يوليو 2012 07:56 م"
	"الإثنين، 16 يوليو 2012 06:30 م"
]

In [8]:
# Arabic month → numeric mapping
month_map = {
    "يناير": "01",
    "فبراير": "02",
    "مارس": "03",
    "أبريل": "04",
    "مايو": "05",
    "يونيو": "06",
    "يوليو": "07",
    "أغسطس": "08",
    "سبتمبر": "09",
    "أكتوبر": "10",
    "نوفمبر": "11",
    "ديسمبر": "12",
}

# Step 1: clean + fix AM/PM safely
expr = (
    pl.col("publish_date")
    .str.replace(r"^.*،\s*", "")   # remove weekday الجزء الأول
    .str.replace(r"\sص$", " AM")   # replace only ending "ص"
    .str.replace(r"\sم$", " PM")   # replace only ending "م"
)

# Step 2: replace Arabic month names
for ar, num in month_map.items():
    expr = expr.str.replace(ar, num)

# Step 3: parse into datetime
df = df.with_columns(
    expr
    .str.strptime(pl.Datetime, "%d %m %Y %I:%M %p", strict=False)
    .alias("date_parsed")
)

In [9]:
df['date_parsed', 'publish_date']

shape: (409_808, 2)
┌─────────────────────┬────────────────────────────────┐
│ date_parsed         ┆ publish_date                   │
│ ---                 ┆ ---                            │
│ datetime[μs]        ┆ str                            │
╞═════════════════════╪════════════════════════════════╡
│ 2026-03-20 07:27:00 ┆ الجمعة، 20 مارس 2026 07:27 ص   │
│ 2026-03-20 08:11:00 ┆ الجمعة، 20 مارس 2026 08:11 ص   │
│ 2026-03-20 08:00:00 ┆ الجمعة، 20 مارس 2026 08:00 ص   │
│ 2026-03-20 07:20:00 ┆ الجمعة، 20 مارس 2026 07:20 ص   │
│ 2026-03-20 07:15:00 ┆ الجمعة، 20 مارس 2026 07:15 ص   │
│ …                   ┆ …                              │
│ 2012-07-17 01:39:00 ┆ الثلاثاء، 17 يوليو 2012 01:39 … │
│ 2017-08-02 18:19:00 ┆ الأربعاء، 02 أغسطس 2017 06:19 … │
│ 2012-07-17 01:26:00 ┆ الثلاثاء، 17 يوليو 2012 01:26 … │
│ 2012-07-16 19:56:00 ┆ الإثنين، 16 يوليو 2012 07:56 م  │
│ 2012-07-16 18:30:00 ┆ الإثنين، 16 يوليو 2012 06:30 م  │
└─────────────────────┴────────────────────────────────┘

In [15]:
ctx = pl.SQLContext(horoscope=df)

In [16]:
result = ctx.execute("select url, content from horoscope where extract(month from date_parsed) = 3 and extract(day from date_parsed) = 21").collect()
result.unique().write_csv("../data/processed/march_21_horoscopes.csv", include_bom=True)

In [41]:
df['images'].head(2)

shape: (2,)
Series: 'images' [list[struct[4]]]
[
	[{"https://img.youm7.com/large/202511120433593359.jpg","تشجيعًا للاستثمار الأخضر.. حوافز لمشروعات المخلفات الزراعية","تشجيعًا للاستثمار الأخضر.. حوافز لمشروعات المخلفات الزراعية",""}]
	[{"https://img.youm7.com/large/202602100642404240_22650.jpg","وزارة الدولة للإعلام والهيئات الإعلامية تدعو قادة الرأى تغليب لغة العقل","وزارة الدولة للإعلام والهيئات الإعلامية تدعو قادة الرأى تغليب لغة العقل",""}]
]